version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    ignore:
      - update-types: ["version-update:semver-patch", "version-update:semver-minor"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    ignore:
      - update-types: ["version-update:semver-patch", "version-update:semver-minor"]
