[workspace]
members = [
    "ndk",
    "ndk-context",
    "ndk-macro",
    "ndk-build",
    "ndk-examples",
    "ndk-glue",
    "ndk-sys",
    "cargo-apk",
]

[patch.crates-io]
cargo-subcommand = { git = "https://github.com/dvc94ch/cargo-subcommand", branch = "master" }
