#include <android/api-level.h>
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include <android/bitmap.h>
#include <android/choreographer.h>
#include <android/configuration.h>
#include <android/data_space.h>
#include <android/dlext.h>
#include <android/hardware_buffer.h>
#include <android/hardware_buffer_jni.h>
#include <android/input.h>
#include <android/keycodes.h>
#include <android/log.h>
#include <android/looper.h>
#include <android/multinetwork.h>
#include <android/NeuralNetworks.h>
#include <android/native_activity.h>
#include <android/native_window.h>
#include <android/native_window_jni.h>
#include <android/ndk-version.h>
#include <android/obb.h>
#include <android/rect.h>
#include <android/sensor.h>
#include <android/set_abort_message.h>
#include <android/sharedmem.h>
#include <android/sharedmem_jni.h>
#include <android/storage_manager.h>
#include <android/surface_texture.h>
#include <android/surface_texture_jni.h>
#include <android/sync.h>
#include <android/trace.h>
#include <android/versioning.h>
#include <android/window.h>

#include <aaudio/AAudio.h>

#include <camera/NdkCameraCaptureSession.h>
#include <camera/NdkCameraManager.h>
#include <camera/NdkCameraWindowType.h>
#include <camera/NdkCameraDevice.h>
#include <camera/NdkCameraMetadata.h>
#include <camera/NdkCaptureRequest.h>
#include <camera/NdkCameraError.h>
#include <camera/NdkCameraMetadataTags.h>

#include <media/NdkImage.h>
#include <media/NdkImageReader.h>
